name = "monitorifes"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./public"

# Agendamento Automático nos 7 horários específicos (Horário de Brasília / UTC-3):
# 08:00 (11 UTC), 12:00 (15 UTC), 14:00 (17 UTC), 17:00 (20 UTC), 18:00 (21 UTC), 20:00 (23 UTC), 23:00 (02 UTC)
[triggers]
crons = [
  "0 11,15,17 * * *",
  "0 2,20,21,23 * * *"
]

# Variáveis de Ambiente e Credenciais do Telegram
[vars]
URL_EDITAL = "https://cachoeiro.ifes.edu.br/processosseletivos/alunos/17163-edital-19-2026-chamada-publica-de-oferta-de-vagas-dos-cursos-tecnicos-concomitante-e-subsequente"
TELEGRAM_CHAT_ID = "5549055698"
TELEGRAM_TOKEN = "8928855109:AAGU-Pa-6btwGYN2qVZhqbQ7M3pO9-aGKnU"

# Configuração de Observabilidade e Logs
[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
